const APP_DEFAULT_LANGUAGE = process.env.REACT_APP_DEFAULT_LANGUAGE ?? "en";
const APP_CONTACT_NUMBER =
  process.env.REACT_APP_CONTACT_NUMBER ?? "000-800-919-1694";

export { APP_DEFAULT_LANGUAGE, APP_CONTACT_NUMBER };
